import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.*;
import sun.audio.*;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KeeganKelley
 */
public class RockPaperScissors extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissors
     */
    public RockPaperScissors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        myLabel = new javax.swing.JLabel();
        computerLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        gameChoice = new javax.swing.JComboBox<>();
        startButton = new javax.swing.JButton();
        myFace = new javax.swing.JLabel();
        computerFace = new javax.swing.JLabel();
        myStatus = new javax.swing.JLabel();
        computerStatus = new javax.swing.JLabel();
        myChoice = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(947, 750));

        myLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        myLabel.setText("Me");

        computerLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        computerLabel.setText("Computer");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Rock, Paper, Scissors Game");

        gameChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Game" }));
        gameChoice.setToolTipText("");
        gameChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gameChoiceItemStateChanged(evt);
            }
        });

        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        myFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normalFace.PNG"))); // NOI18N
        myFace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myFaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myFaceMouseExited(evt);
            }
        });

        computerFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/normalFace.PNG"))); // NOI18N
        computerFace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                computerFaceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                computerFaceMouseExited(evt);
            }
        });

        myStatus.setText("My Status");

        computerStatus.setText("Computer Status");

        myChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Paper", "Scissors" }));
        myChoice.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                myChoicePopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myFace)
                        .addGap(90, 90, 90)
                        .addComponent(myChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(computerFace))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton)
                            .addComponent(gameChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(myLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerLabel)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(myStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerStatus)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(gameChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myLabel)
                            .addComponent(computerLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(myFace))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(myChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))))
                    .addComponent(computerFace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myStatus)
                    .addComponent(computerStatus))
                .addGap(153, 153, 153))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        int index = gameChoice.getSelectedIndex();
        switch(index)
        {
            case 0:
                theFinalWinner = oneGame();
                changeFaces(theFinalWinner);
                break;
            /*case 1:
                theFinalWinner = playFiveGames();
                changeFaces(theFinalWinner);
                break;
            case 2:
                theFinalWinner = playInfiniteGames();
                changeFaces(theFinalWinner);
                break;
                */
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void gameChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gameChoiceItemStateChanged
        // TODO add your handling code here:
        int index = gameChoice.getSelectedIndex();
        switch(index)
        {
            case 0:
                oneGame();
           /* case 1:
                playFiveGames();
            case 2:
                playInfiniteGames();
                */
        }
    }//GEN-LAST:event_gameChoiceItemStateChanged

    private void myChoicePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_myChoicePopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_myChoicePopupMenuWillBecomeVisible

    private void myFaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFaceMouseEntered
        // TODO add your handling code here:
        try{
            if(theFinalWinner.equals("YOU"))
                in = new FileInputStream(applauseFile);
            else if (theFinalWinner.equals("COMPUTER"))            
                in = new FileInputStream(booFile);
            
            // create an audiostream from the inputstream
            audioStream = new AudioStream(in);
            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        }
        catch (Exception e)
        {
            System.out.println("Audio file couldn't play!");
        }
    }//GEN-LAST:event_myFaceMouseEntered

    private void myFaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFaceMouseExited
        // TODO add your handling code here:
        AudioPlayer.player.stop(audioStream); 
    }//GEN-LAST:event_myFaceMouseExited

    private void computerFaceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerFaceMouseEntered
        // TODO add your handling code here:
        try{
            if(theFinalWinner.equals("COMPUTER"))
                in = new FileInputStream(applauseFile);
            else if (theFinalWinner.equals("YOU"))            
                in = new FileInputStream(booFile);
            
            // create an audiostream from the inputstream
            audioStream = new AudioStream(in);
            // play the audio clip with the audioplayer class
            AudioPlayer.player.start(audioStream);
        }
        catch (Exception e)
        {
            System.out.println("Audio file couldn't play!");
        }
    }//GEN-LAST:event_computerFaceMouseEntered

    private void computerFaceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerFaceMouseExited
        // TODO add your handling code here:
        AudioPlayer.player.stop(audioStream); 
    }//GEN-LAST:event_computerFaceMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissors().setVisible(true);
            }
        });
    }
    
    private String oneGame()
    {
        String theWinner = "";
        String myHand = myChoice.getSelectedItem().toString();
        int compIndex = ((int)(Math.random() * 100) % 3);
        
        theWinner = whoIsTheWinner(myHand, computerHand[compIndex]);
        
        System.out.println("The Computer chose " + computerHand[compIndex]);
        
        titleLabel.setText("Thanks For Playing!");
        
        return theWinner;
    }
    
    private String playFiveGames(){
	//enter your code here
        String theWinner = "TIE";
        String yourHand;
        String compHand;
        
        //example code below.  You have to implement your own code here
        for(int index = 0; index<5; ++index)
        {
            int compIndex = ((int)(Math.random() * 100) % 3);
            compHand = computerHand[compIndex];
            yourHand = myChoice.getSelectedItem().toString();//get from scanner
            theWinner = whoIsTheWinner(yourHand, compHand);
        }
        return theWinner;
    }

    private String playInfiniteGames(){
    	String myHand, compHand,theWinner="TIE";
        int response = JOptionPane.showConfirmDialog(null, "Keep Playing?", "Computer is asking you...", JOptionPane.YES_NO_OPTION);
        while(response == JOptionPane.YES_OPTION)
        {
            int compIndex = ((int)(Math.random() * 100) % 3);
            compHand = computerHand[compIndex];
            myHand = myChoice.getSelectedItem().toString();//get from scanner
            theWinner = whoIsTheWinner(myHand, compHand);
        }
        return theWinner;
    }
    
    private void changeFaces(String fWinner){
        switch (fWinner){
            case "YOU":
            myFace.setIcon(happyFace);
            computerFace.setIcon(sadFace);
            myStatus.setText("Winner");
            computerStatus.setText("Loser");
            break;
            case "COMPUTER":
            myFace.setIcon(sadFace);               
            computerFace.setIcon(happyFace);
            myStatus.setText("Loser");
            computerStatus.setText("Winner");
            break;
            case "TIE":
            myFace.setIcon(normalFace);               
            computerFace.setIcon(normalFace);
            myStatus.setText("TIE");
            computerStatus.setText("TIE");
        }
    }
    
    private String whoIsTheWinner(String myHand, String compHand)
    {
        String theWinner = "";
        switch (myHand)
        {
            case "Rock":
                if(compHand.equals("Paper"))
                    theWinner="COMPUTER";
                if (compHand.equals("Scissors"))
                    theWinner="YOU";
                if (compHand.equals("Rock"))
                    theWinner="TIE";
            break;
            case "Paper":
                if(compHand.equals("Rock"))
                    theWinner="YOU";
                else if (compHand.equals("Scissors"))
                    theWinner="COMPUTER";                
            break;
            case "Scissors":
                if(compHand.equals("Rock"))
                    theWinner="COMPUTER";
                else if (compHand.equals("Paper"))
                    theWinner="YOU";
            break;
        }
        return theWinner;
    }
    
    
    String[] computerHand = {"Rock","Paper","Scissors"};
    String theFinalWinner = "";
    
    ImageIcon sadFace = new ImageIcon("C:\\Users\\kandj\\Terminal\\Java2\\FinalProject\\src\\sadFace.png");
    ImageIcon happyFace = new ImageIcon("C:\\Users\\kandj\\Terminal\\Java2\\FinalProject\\src\\happyFace.png");
    ImageIcon normalFace = new ImageIcon("C:\\Users\\kandj\\Terminal\\Java2\\FinalProject\\src\\normalFace.png");
    
    String booFile = ("C:\\Users\\kandj\\Terminal\\Java2\\FinalProject\\src\\boo.wav");
    String applauseFile = ("C:\\Users\\kandj\\Terminal\\Java2\\FinalProject\\src\\applause.wav");
    AudioStream audioStream;
    InputStream in;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computerFace;
    private javax.swing.JLabel computerLabel;
    private javax.swing.JLabel computerStatus;
    private javax.swing.JComboBox<String> gameChoice;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> myChoice;
    private javax.swing.JLabel myFace;
    private javax.swing.JLabel myLabel;
    private javax.swing.JLabel myStatus;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
